version: '3'
services:
  redis-1:
    container_name: "redis-1"
    image: redis:6.0-alpine
    ports:
      - 7000:7000
      - 17000:17000
    volumes:
      - "./redis/redis.conf:/etc/redis.conf"
    command: redis-server /etc/redis.conf --port 7000
    network_mode: "host"
  redis-2:
    container_name: "redis-2"
    image: redis:6.0-alpine
    ports:
      - 7001:7001
      - 17001:17001
    volumes:
      - "./redis/redis.conf:/etc/redis.conf"
    command: redis-server /etc/redis.conf --port 7001
    network_mode: "host"
  redis-3:
    container_name: "redis-3"
    image: redis:6.0-alpine
    ports:
      - 7002:7002
      - 17002:17002
    volumes:
      - "./redis/redis.conf:/etc/redis.conf"
    command: redis-server /etc/redis.conf --port 7002
    network_mode: "host"
  redis-4:
    container_name: "redis-4"
    image: redis:6.0-alpine
    ports:
      - 7003:7003
      - 17003:17003
    volumes:
      - "./redis/redis.conf:/etc/redis.conf"
    command: redis-server /etc/redis.conf --port 7003
    network_mode: "host"
  redis-5:
    container_name: "redis-5"
    image: redis:6.0-alpine
    ports:
      - 7004:7004
      - 17004:17004
    volumes:
      - "./redis/redis.conf:/etc/redis.conf"
    command: redis-server /etc/redis.conf --port 7004
    network_mode: "host"
  redis-6:
    container_name: "redis-6"
    image: redis:6.0-alpine
    ports:
      - 7005:7005
      - 17005:17005
    volumes:
      - "./redis/redis.conf:/etc/redis.conf"
    command: redis-server /etc/redis.conf --port 7005
    network_mode: "host"
  redis-creator:
    container_name: "redis-creator"
    image: redis:6.0-alpine
    command: redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 --cluster-replicas 1 --cluster-yes
    network_mode: "host"
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6