version: '3.1'
volumes:
  data-redis-cluster-1:
  data-redis-cluster-2:
  data-redis-cluster-3:
  data-redis-cluster-4:
  data-redis-cluster-5:
  data-redis-cluster-6:
  data-redis-cluster-founder:
networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
services:
  redis-node-1:
    image: 10.100.30.100:5000/redis-cluster
    networks:
      lan:
        ipv4_address: 192.168.0.11
    restart: always
    ports:
      - 63791:6379
    volumes:
      - data-redis-cluster-1:/data
  redis-node-2:
    image: 10.100.30.100:5000/redis-cluster
    networks:
      lan:
        ipv4_address: 192.168.0.12
    restart: always
    ports:
      - 63792:6379
    volumes:
      - data-redis-cluster-2:/data
  redis-node-3:
    image: 10.100.30.100:5000/redis-cluster
    networks:
      lan:
        ipv4_address: 192.168.0.13
    restart: always
    ports:
      - 63793:6379
    volumes:
      - data-redis-cluster-3:/data
  redis-node-4:
    image: 10.100.30.100:5000/redis-cluster
    networks:
      lan:
        ipv4_address: 192.168.0.14
    restart: always
    ports:
      - 63794:6379
    volumes:
      - data-redis-cluster-4:/data
  redis-node-5:
    image: 10.100.30.100:5000/redis-cluster
    networks:
      lan:
        ipv4_address: 192.168.0.15
    restart: always
    ports:
      - 63795:6379
    volumes:
      - data-redis-cluster-5:/data
  redis-node-6:
    image: 10.100.30.100:5000/redis-cluster
    networks:
      lan:
        ipv4_address: 192.168.0.16
    restart: always
    ports:
      - 63796:6379
    volumes:
      - data-redis-cluster-6:/data
  redis-cluster-founder:
    image: 10.100.30.100:5000/redis-cluster
    networks:
      lan:
        ipv4_address: 192.168.0.10
    volumes:
      - data-redis-cluster-founder:/data
    command: sh /create-cluster.sh
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6